---

aws_security_groups_vars:
  - name: apache
    description: apache
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"

aws_iam_roles_vars:
  - name: apache
