---

- name: install apache
  yum: >
    name={{ item }}
    state=present
  with_items:
    - httpd

- name: Ensure apache is running
  service:
    name=httpd
    state=started

- name: Ensure httpd is enabled
  service:
    name=httpd
    enabled=yes